use serde::{Deserialize, Serialize}; /*
                                      * lustre API (autopush)
                                      *
                                      * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
                                      *
                                      * The version of the OpenAPI document: v1alpha
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

use crate::google_rest_apis::lustre_v1alpha::models;

/// GcsBucket : Cloud Storage as the source of a data transfer.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GcsBucket {
    /// Required. URI to a Cloud Storage bucket in the format: `gs://`.
    #[serde(rename = "uri", skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
}

impl GcsBucket {
    /// Cloud Storage as the source of a data transfer.
    pub fn new() -> GcsBucket {
        GcsBucket { uri: None }
    }
}
