use serde::{Deserialize, Serialize}; /*
                                      * lustre API (autopush)
                                      *
                                      * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
                                      *
                                      * The version of the OpenAPI document: v1alpha
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

use crate::google_rest_apis::lustre_v1alpha::models;

/// Instance : Message describing Instance object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Instance {
    /// Required. Capacity of the instance in GiB
    #[serde(rename = "capacityGib", skip_serializing_if = "Option::is_none")]
    pub capacity_gib: Option<String>,
    /// Output only. [Output only] Create time stamp
    #[serde(rename = "createTime", skip_serializing_if = "Option::is_none")]
    pub create_time: Option<String>,
    /// Optional. Description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Required. Immutable. Filesystem Name for Lustre.
    #[serde(rename = "filesystem", skip_serializing_if = "Option::is_none")]
    pub filesystem: Option<String>,
    /// Optional. Labels as key value pairs
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<std::collections::HashMap<String, String>>,
    /// Output only. Mount point of the instance given by IP address and filesystem name and is in the format of {ip_address}@tcp:/{filesystem}.
    #[serde(rename = "mountPoint", skip_serializing_if = "Option::is_none")]
    pub mount_point: Option<String>,
    /// Identifier. name of resource
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Required. Immutable. VPC Network full name. Must be in a form 'projects/{project}/global/networks/{network}'. {project} is a project number, as in '12345' {network} is network name.
    #[serde(rename = "network", skip_serializing_if = "Option::is_none")]
    pub network: Option<String>,
    /// Output only. State of the instance
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<State>,
    /// Output only. [Output only] Update time stamp
    #[serde(rename = "updateTime", skip_serializing_if = "Option::is_none")]
    pub update_time: Option<String>,
}

impl Instance {
    /// Message describing Instance object
    pub fn new() -> Instance {
        Instance {
            capacity_gib: None,
            create_time: None,
            description: None,
            filesystem: None,
            labels: None,
            mount_point: None,
            name: None,
            network: None,
            state: None,
            update_time: None,
        }
    }
}
/// Output only. State of the instance
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "STATE_UNSPECIFIED")]
    StateUnspecified,
    #[serde(rename = "ACTIVE")]
    Active,
    #[serde(rename = "CREATING")]
    Creating,
    #[serde(rename = "DELETING")]
    Deleting,
    #[serde(rename = "UPGRADING")]
    Upgrading,
    #[serde(rename = "REPAIRING")]
    Repairing,
    #[serde(rename = "STOPPED")]
    Stopped,
}

impl Default for State {
    fn default() -> State {
        Self::StateUnspecified
    }
}
