use serde::{Deserialize, Serialize}; /*
                                      * lustre API (autopush)
                                      *
                                      * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
                                      *
                                      * The version of the OpenAPI document: v1alpha
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

use crate::google_rest_apis::lustre_v1alpha::models;

/// LustrePath : LustrePath represents a path in the Lustre filesystem.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LustrePath {
    /// Optional. Root directory path to the Lustre filesystem, starting with `/`. Defaults to `/` if unset.
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
}

impl LustrePath {
    /// LustrePath represents a path in the Lustre filesystem.
    pub fn new() -> LustrePath {
        LustrePath { path: None }
    }
}
