[package]
name = "lustre-client"
version = "0.1.0"
authors = ["jparris@ddn.com"]
edition = "2021"

[dependencies]
gcloud-sdk = { path = "./../../gcloud-sdk", features = ["rest", "google-rest-lustre-v1alpha"] }
tokio = { version = "1.20", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version ="0.3", features = ["env-filter"] }
futures = "0.3"
bytes = "1.2"
